# Generated by Django 4.0.4 on 2022-06-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deckmodel',
            options={'verbose_name': 'Deck', 'verbose_name_plural': 'Decks'},
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_interval', models.IntegerField()),
                ('front', models.CharField(max_length=500)),
                ('new_word', models.CharField(max_length=500)),
                ('back', models.CharField(max_length=500)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endeavorapp.deckmodel')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
