# Generated by Django 4.0.5 on 2022-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0004_card_word_wordincard_rename_deckmodel_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
