# Generated by Django 4.0.5 on 2022-07-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0005_alter_card_deadline_alter_card_study_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='back',
        ),
    ]
