# Generated by Django 4.0.5 on 2022-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0006_remove_card_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='front',
            new_name='front_text',
        ),
        migrations.AddField(
            model_name='card',
            name='front_audio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
