# Generated by Django 4.0.5 on 2022-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0007_rename_front_card_front_text_card_front_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
