# Generated by Django 4.0.5 on 2022-07-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0008_alter_word_image_alter_word_pronunciation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordincard',
            old_name='dict_entry',
            new_name='word',
        ),
    ]
