# Generated by Django 4.0.5 on 2022-07-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0011_rename_display_order_wordincard_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordincard',
            unique_together={('card', 'word', 'order')},
        ),
    ]
