# Generated by Django 4.0.5 on 2022-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0013_alter_wordincard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
