# Generated by Django 4.0.5 on 2022-07-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0015_alter_word_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='pronunciation',
            new_name='phonetic',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='text',
        ),
    ]
