# Generated by Django 4.0.5 on 2022-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0016_rename_pronunciation_word_phonetic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='front_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('text', 'definition')},
        ),
    ]
