# Generated by Django 4.0.5 on 2022-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0017_alter_card_front_audio_alter_word_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
