# Generated by Django 4.0.5 on 2022-08-02 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endeavorapp', '0018_word_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
