# Generated by Django 4.0.5 on 2022-08-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0023_remove_card_deadline_remove_card_study_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
