# Generated by Django 4.0.5 on 2022-08-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0025_rename_studiedcard_usercard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='users',
        ),
    ]
