# Generated by Django 4.0.5 on 2022-08-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0026_rename_user_card_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
