# Generated by Django 4.0.5 on 2022-08-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0027_alter_card_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('deck', 'order')},
        ),
    ]
