# Generated by Django 4.0.5 on 2022-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0028_alter_card_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
