# Generated by Django 4.0.5 on 2022-08-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endeavorapp', '0029_alter_card_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='order',
            new_name='order_in_deck',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('deck', 'order_in_deck')},
        ),
    ]
